package com.cky.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BOOK".
 */
public class Book {

    private Long id;
    private String bookname;
    private String bookisbn;
    private String bookid;
    private String requestid;

    public Book() {
    }

    public Book(Long id) {
        this.id = id;
    }

    public Book(Long id, String bookname, String bookisbn, String bookid, String requestid) {
        this.id = id;
        this.bookname = bookname;
        this.bookisbn = bookisbn;
        this.bookid = bookid;
        this.requestid = requestid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBookname() {
        return bookname;
    }

    public void setBookname(String bookname) {
        this.bookname = bookname;
    }

    public String getBookisbn() {
        return bookisbn;
    }

    public void setBookisbn(String bookisbn) {
        this.bookisbn = bookisbn;
    }

    public String getBookid() {
        return bookid;
    }

    public void setBookid(String bookid) {
        this.bookid = bookid;
    }

    public String getRequestid() {
        return requestid;
    }

    public void setRequestid(String requestid) {
        this.requestid = requestid;
    }

}
